name: CD

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - '*' # Test all pushed tags
    tags:
      - '*' # Test all pushed tags

  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted
env:
  RELEASE: release

jobs:
  build:
    runs-on: ubuntu-latest
    name: Simply build for deployment
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: npm install
      run: |
        npm install --legacy-peer-deps

    - name: npm run build
      run: |
        SKIP_PREFLIGHT_CHECK=true npm run build
