name: CD

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master # Push events on master + devel branch
      - devel
    tags:
      - '*' # Test all pushed tags

  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted
  status: {}
env:
  RELEASE: release

jobs:
  build:
    runs-on: ubuntu-latest
    name: Simply build for deployment
    steps:

    - uses: actions/checkout@v1      
    - name: Checkout submodules
      run: |
        echo Checkout submodules
        git submodule sync
        git submodule update --init --recursive

    - name: npm install
      run: |
        npm install

    - name: npm run build
      run: |
        npm run build
