name: CD

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'devel'
      - 'main'
      - 'master'
    tags:
      - '*' # Test all pushed tags

  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted
env:
  RELEASE: release
  ID_RSA_PRIV: ${{ secrets.ID_RSA_PRIV }}
  ID_RSA_PUB: ${{ secrets.ID_RSA_PUB }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Simply build for deployment
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: install and build
      run: |
        bun install --legacy-peer-deps
        SKIP_PREFLIGHT_CHECK=true bun run build

    - name: Upload
      if: github.event_name == 'push' && (github.ref == 'refs/heads/devel' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
      run: |
        echo "$ID_RSA_PRIV" > id_rsa_sftp
        echo "$ID_RSA_PUB" > id_rsa_sftp.pub
        chmod 600 id_rsa_sftp
        chmod 644 id_rsa_sftp.pub
        ./scripts/sftp_put.sh
        rm id_rsa_sftp
        rm id_rsa_sftp.pub